[project]
name = "imflatfield"
version = "0.1.0"
description = "Flat field correction for 16-bit grayscale images"
readme = "README.md"
authors = [{name="Lam Tran", email="lam.tran@fau.de"}]
requires-python = ">=3.13"
dependencies = [
    "numpy==2.2.3",
    "opencv-python==4.11.0.86",
]
